global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'musinsa-monitor'

scrape_configs:
  # Spring Boot 애플리케이션 메트릭
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  # Redis 메트릭
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']




